---
# application tasks to be customized and to run after the main provision
- name: Install PHPUnit
  get_url: url=https://phar.phpunit.de/phpunit.phar dest=/usr/local/bin/phpunit mode=555

- name: Install PHP-CS fixer
  get_url: url=http://get.sensiolabs.org/php-cs-fixer.phar dest=/usr/local/bin/php-cs-fixer mode=555

- name: Install Phing
  get_url: url=http://www.phing.info/get/phing-latest.phar dest=/usr/local/bin/phing mode=555

- name: Install Box project
  get_url: url=https://github.com/box-project/box2/releases/download/2.7.2/box-2.7.2.phar dest=/usr/local/bin/box mode=555

- name: Clone PHP Git Hooks repo
  git: repo=https://github.com/intaro/php-git-hooks.git dest=/vagrant/infrastructure/php-git-hooks

- name: Clone Git Subsplit repo
  git: repo=https://github.com/dflydev/git-subsplit.git dest=/vagrant/infrastructure/git-subsplit

- name: Configure more user friendly list of aliases
  lineinfile:
    dest: ~{{ console_user | default(ansible_user) }}/.bashrc
    line: "alias {{ item.alias }}='{{ item.command }}'"
    regexp: "^alias {{ item.alias }}="
    state: present
  with_items:
    - { alias: ll, command: "ls -lFh" }
    - { alias: la, command: "ls -lFhA" }
    - { alias: l,  command: "ls -CF" }
    - { alias: ..., command: "cd .."}
