---
# application tasks to be customized and to run after the main provision
- name: Install PHPUnit
  get_url: url=https://phar.phpunit.de/phpunit.phar dest=/usr/local/bin/phpunit mode=555

- name: Install PHP-CS fixer
  get_url: url=http://get.sensiolabs.org/php-cs-fixer.phar dest=/usr/local/bin/php-cs-fixer mode=555

- name: Install Phing
  get_url: url=http://www.phing.info/get/phing-latest.phar dest=/usr/local/bin/phing mode=555

- name: Install Box project
  get_url: url=https://github.com/box-project/box2/releases/download/2.7.2/box-2.7.2.phar dest=/usr/local/bin/box mode=555

- name: Clone PHP Git Hooks repo
  git: repo=https://github.com/intaro/php-git-hooks.git dest=/vagrant/infrastructure/php-git-hooks

- name: Clone Git Subsplit repo
  git: repo=https://github.com/dflydev/git-subsplit.git dest=/vagrant/infrastructure/git-subsplit

- name: Create Git prompt Bash script
  template:
    src=.git-prompt.sh.tpl
    dest=/home/vagrant/.git-prompt.sh
    owner=vagrant group=vagrant mode=0644

- name: Create Bash configuration file
  template:
    src=.bashrc.tpl
    dest=/home/vagrant/.bashrc
    owner=vagrant group=vagrant mode=0644

- name: Create Bash alias file
  template:
    src=.bash_aliases.tpl
    dest=/home/vagrant/.bash_aliases
    owner=vagrant group=vagrant mode=0644

- name: Create global gitignore file
  template:
    src=.gitignore_global.tpl
    dest=/home/vagrant/.gitignore_global
    owner=vagrant group=vagrant mode=0644

- name: Configure global gitignore
  shell: git config --global core.excludesfile /home/vagrant/.gitignore_global
