---
# application tasks to be customized and to run after the main provision
- name: Install PHPUnit
  get_url: url=https://phar.phpunit.de/phpunit.phar dest=/usr/local/bin/phpunit mode=555

- name: Install PHP-CS fixer
  get_url: url=http://get.sensiolabs.org/php-cs-fixer.phar dest=/usr/local/bin/php-cs-fixer mode=555

- name: Install Phing
  get_url: url=http://www.phing.info/get/phing-latest.phar dest=/usr/local/bin/phing mode=555

- name: Clone Git Subsplit repo
  git: repo=https://github.com/dflydev/git-subsplit.git dest=/tmp/git-subsplit

- name: Install Git Subsplit
  sudo: yes
  shell: /tmp/git-subsplit/install.sh

- name: Install PHP Git Hooks
  git: repo=https://github.com/intaro/php-git-hooks.git dest=/vagrant/infrastructure/php-git-hooks

- name: Download Box project
  get_url: url=https://box-project.github.io/box2/installer.php dest=/tmp

- name: Build Box application
  shell: php /tmp/installer.php

- name: Move Box application
  copy: src=/tmp/box.phar dest=/usr/local/bin/box.phar mode=555

- name: Rename Box application
  sudo: yes
  shell: mv /usr/local/bin/box.phar /usr/local/bin/box

- name: More User Friendly List Aliases
  lineinfile:
    dest: ~{{ console_user | default(ansible_ssh_user) }}/.bashrc
    line: "alias {{ item.alias }}='{{ item.command }}'"
    regexp: "^alias {{ item.alias }}="
    state: present
  with_items:
    - { alias: ll, command: "ls -lFh" }
    - { alias: la, command: "ls -lFhA" }
    - { alias: l,  command: "ls -CF" }
    - { alias: ..., command: "cd .."}
